### ISSUE TITLE
Sprite update with an "active" h interruption

### ISSUE THREAD

**Issue by David-Vandensteen** [astrofra/megadrive-experiments#3]
In water_fx sample, the logo sprite cannot be updated "normally" in main loop...
Tested:

> before VDP_waitVSync();
> after VDP_waitVSync();
> In a callBak on Verticalblank interruption

tested with deactivate interruptions before the update with an reactivate after ...
Nothing ...

I will try to reproduce this "problem" with a more simple sample
Maybe a limitation, a bug with SGDK or misunderstanding with interruptions ...

**Comment by David-Vandensteen** [comment]
Its not the horizontal interruptions or callBack that interferes ...
This simple test work ...

```
static void test(){
    u16 vblCount = 0;
    u16 hCount = 0;
    char hCountStr[4];
    Sprite sprites[1];
    SYS_disableInts();
    VDP_setPalette(PAL1, pirate_logo.palette->data);
    SYS_enableInts();
    SPR_init(354);
    static void hBlank(){
        hCount++;
    }
    SPR_initSprite(&sprites[0], &pirate_logo, 0, 0, TILE_ATTR_FULL(PAL1, TRUE, FALSE, FALSE, 0));
    VDP_setHInterrupt(1);
    SYS_setHIntCallback(&hBlank);

    while (1){
        VDP_waitVSync();
        vblCount++;
        intToStr(hCount, hCountStr, 4);
        VDP_drawText(hCountStr, 10, 20);
        SPR_setPosition(&sprites[0],(sinFix16(vblCount) % 320 ),0);
        SPR_update(&sprites, 1);
    }
}
```

**Comment by astrofra** [comment]
Well,it's not that "moving a sprite in the main loop" doesn't work.
I simply noticed that "calling SPR_update() in the main loop" rendered the hblank function almost useless :/

**Comment by astrofra** [comment]
Issue closed. Updating the sprites must be done, either in the main loop, either is the last hblank, either in the vblank.
